# Generated by Django 4.0.4 on 2022-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('delivering', 'delivering'), ('received', 'received')], default='processing', max_length=10),
        ),
    ]
