type = "function"

[data]
type = "dict"

[data.data]

[data.data.__globals__]
type = "dict"

[data.data.__globals__.data]

[data.data.attributes]
type = "dict"

[data.data.attributes.data]

[data.data.attributes.data.__name__]
type = "str"
data = "add"

[data.data.attributes.data.__defaults__]

[data.data.attributes.data.__closure__]

[data.data.attributes.data.__code__]
type = "codeobject"

[data.data.attributes.data.__code__.data]
type = "dict"

[data.data.attributes.data.__code__.data.data]

[data.data.attributes.data.__code__.data.data.co_argcount]
type = "int"
data = 2

[data.data.attributes.data.__code__.data.data.co_cellvars]
type = "tuple"
data = []

[data.data.attributes.data.__code__.data.data.co_code]
type = "bytes"
data = [124, 0, 124, 1, 23, 0, 83, 0]

[data.data.attributes.data.__code__.data.data.co_consts]
type = "tuple"

[[data.data.attributes.data.__code__.data.data.co_consts.data]]

[data.data.attributes.data.__code__.data.data.co_filename]
type = "str"
data = "/home/leshii/lab2_isp/objects_for_test.py"

[data.data.attributes.data.__code__.data.data.co_firstlineno]
type = "int"
data = 52

[data.data.attributes.data.__code__.data.data.co_flags]
type = "int"
data = 67

[data.data.attributes.data.__code__.data.data.co_freevars]
type = "tuple"
data = []

[data.data.attributes.data.__code__.data.data.co_kwonlyargcount]
type = "int"
data = 0

[data.data.attributes.data.__code__.data.data.co_lnotab]
type = "bytes"
data = [0, 1]

[data.data.attributes.data.__code__.data.data.co_name]
type = "str"
data = "add"

[data.data.attributes.data.__code__.data.data.co_names]
type = "tuple"
data = []

[data.data.attributes.data.__code__.data.data.co_nlocals]
type = "int"
data = 2

[data.data.attributes.data.__code__.data.data.co_posonlyargcount]
type = "int"
data = 0

[data.data.attributes.data.__code__.data.data.co_stacksize]
type = "int"
data = 2

[data.data.attributes.data.__code__.data.data.co_varnames]
type = "tuple"

[[data.data.attributes.data.__code__.data.data.co_varnames.data]]
type = "str"
data = "a"

[[data.data.attributes.data.__code__.data.data.co_varnames.data]]
type = "str"
data = "b"
