# Generated by Django 4.0.4 on 2022-05-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0002_category_product_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
